# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: threats.proto for package 'rpc'

require 'grpc'
require 'app/proto/threats_pb'

module Rpc
  module Threats
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'rpc.Threats'

      rpc :CreateThreat, ::Rpc::Threat, ::Rpc::Threat
    end

    Stub = Service.rpc_stub_class
  end
end
