# docker-compose.yml
version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: zrp.rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  socket.io.server:
    image: leandrolasnor/ruby:zrp
    container_name: zrp.socket.io.server
    command: sh -c "yarn --cwd ./socket.io/server start"

  socket.io.client:
    image: leandrolasnor/ruby:zrp
    container_name: zrp.socket.io.client
    command: sh -c "yarn --cwd ./socket.io/client start"
    depends_on:
      - rabbitmq
      - socket.io.server

  sneakers:
    image: leandrolasnor/ruby:zrp
    container_name: zrp.sneakers
    command: sh -c "bundle exec rake sneakers:run"
    depends_on:
      - socket.io.client
      - db

  redis:
    image: redis:alpine
    container_name: zrp.redis
    environment:
        ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
        - "6379:6379"

  resque:
    image: leandrolasnor/ruby:zrp
    container_name: zrp.resque
    command: sh -c "foreman start"
    depends_on:
      - redis
      - db

  api:
    image: leandrolasnor/ruby:zrp
    container_name: zrp.api
    stdin_open: true
    tty: true
    command: sh
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db

  db:
    image: bitnami/postgresql:latest
    container_name: zrp.postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: zrp
    ports:
      - "5432:5432"
