const WS_ACTION_TYPES = new Set([
  'WIDGET_HEROES_WORKING_FETCHED',
  'WIDGET_THREATS_DISABLED_FETCHED',
  'WIDGET_BATTLES_LINEUP_FETCHED',
  'WIDGET_AVERAGE_SCORE_FETCHED',
  'WIDGET_AVERAGE_TIME_TO_MATCH_FETCHED',
  'WIDGET_SUPER_HERO_FETCHED',
  'WIDGET_THREATS_DISTRIBUTION_FETCHED',
  'WIDGET_HEROES_DISTRIBUTION_FETCHED',
])

export default WS_ACTION_TYPES
