---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/heroes/list":
    get:
      summary: list heroes
      tags:
      - Heroes
      parameters:
      - name: page
        in: query
        description: pagination
        schema:
          type: integer
      - name: per_page
        in: query
        description: pagination
        schema:
          type: integer
      responses:
        '200':
          description: successful
  "/v1/heroes":
    post:
      summary: create hero
      tags:
      - Heroes
      security:
      - ApiKeyAuth: []
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                rank:
                  type: integer
                lat:
                  type: number
                lng:
                  type: number
              required:
              - name
              - rank
              - lat
              - lng
  "/v1/heroes/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: show hero
      tags:
      - Heroes
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: successful
    patch:
      summary: update hero
      tags:
      - Heroes
      security:
      - ApiKeyAuth: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                lat:
                  type: numeric
                lng:
                  type: numeric
              required:
              - name
              - lat
              - lng
    put:
      summary: update hero
      tags:
      - Heroes
      security:
      - ApiKeyAuth: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                rank:
                  type: integer
                lat:
                  type: numeric
                lng:
                  type: numeric
              required:
              - name
              - rank
              - lat
              - lng
    delete:
      summary: destroy hero
      tags:
      - Heroes
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: successful
  "/v1/metrics/dashboard":
    get:
      summary: dashboard metric
      tags:
      - Metrics
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: successful
  "/v1/threats/historical":
    get:
      summary: threat history
      tags:
      - Threats
      security:
      - ApiKeyAuth: []
      parameters:
      - name: page
        in: query
        description: pagination
        schema:
          type: integer
      - name: per_page
        in: query
        description: pagination
        schema:
          type: integer
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
