---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/heroes/search":
    get:
      summary: search heroes
      tags:
      - Heroes
      parameters:
      - name: query
        in: query
        description: query
        example: Silva
        schema:
          type: string
      - name: page
        in: query
        description: pagination
        example: '1'
        schema:
          type: integer
      - name: per_page
        in: query
        description: pagination
        example: '3'
        schema:
          type: integer
      - name: sort
        in: query
        description: sort
        required: false
        example: name:desc
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/v1/heroes/list":
    get:
      summary: list heroes
      tags:
      - Heroes
      parameters:
      - name: page
        in: query
        description: pagination
        example: '1'
        schema:
          type: integer
      - name: per_page
        in: query
        description: pagination
        example: '3'
        schema:
          type: integer
      responses:
        '200':
          description: successful
  "/v1/heroes":
    post:
      summary: create hero
      tags:
      - Heroes
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Forrest Gump
                rank:
                  type: integer
                  example: '2'
                lat:
                  type: number
                  example: -45.89876577878768
                lng:
                  type: number
                  example: 66.89879054787713
              required:
              - name
              - rank
              - lat
              - lng
  "/v1/heroes/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: show hero
      tags:
      - Heroes
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  rank:
                    type: string
                  lat:
                    type: string
                  lng:
                    type: string
                required:
                - name
                - rank
                - lat
                - lng
    patch:
      summary: update hero
      tags:
      - Heroes
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  example: '1'
                name:
                  type: string
                  example: Silva
                lat:
                  type: numeric
                  example: 5.529871874122506
                lng:
                  type: numeric
                  example: -162.4156876628909
              required:
              - id
              - name
              - lat
              - lng
    put:
      summary: update hero
      tags:
      - Heroes
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  example: '1'
                name:
                  type: string
                  example: Silva
                rank:
                  type: integer
                  example: '0'
                lat:
                  type: numeric
                  example: -22.86210918520104
                lng:
                  type: numeric
                  example: -27.26000247930017
              required:
              - id
              - name
              - rank
              - lat
              - lng
    delete:
      summary: destroy hero
      tags:
      - Heroes
      responses:
        '200':
          description: successful
  "/v1/metrics/dashboard":
    get:
      summary: dashboard metric
      tags:
      - Metrics
      responses:
        '200':
          description: successful
  "/v1/threats/historical":
    get:
      summary: threat history
      tags:
      - Threats
      parameters:
      - name: page
        in: query
        description: pagination
        schema:
          type: integer
      - name: per_page
        in: query
        description: pagination
        schema:
          type: integer
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
