# docker-compose.yml
version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: zrp.rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
    - 5672
    - 15672

  redis:
    image: redis:alpine
    container_name: zrp.redis
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
    - 6379

  api:
    image: leandrolasnor/ruby:zrp
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: zrp.api
    stdin_open: true
    tty: true
    command: sh
    ports:
    - 3000:3000
    - 3001:3001
    - 3003
    depends_on:
    - redis
    - db

  db:
    image: bitnami/postgresql:latest
    container_name: zrp.postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: zrp
    ports:
    - 5432

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: zrp.meilisearch
    environment:
      MEILI_MASTER_KEY: key
      MEILI_NO_ANALYTICS: true
    ports:
    - 7700:7700
