# docker-compose.yml
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: zrp.rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
    - 5672
    - 15672
    deploy:
      resources:
        limits:
          memory: 300m

  redis:
    image: redis:alpine
    container_name: zrp.redis
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
    - 6379
    deploy:
      resources:
        limits:
          memory: 50m

  api:
    image: leandrolasnor/ruby:zrp
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: zrp.api
    stdin_open: true
    tty: true
    command: sh
    ports:
    - 3000:3000
    - 3001:3001
    - 3003
    depends_on:
    - redis
    - db
    deploy:
      resources:
        limits:
          memory: 2G

  db:
    image: bitnami/postgresql:latest
    container_name: zrp.postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: zrp
    ports:
    - 5432
    deploy:
      resources:
        limits:
          memory: 300m

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: zrp.meilisearch
    environment:
      MEILI_MASTER_KEY: key
      MEILI_NO_ANALYTICS: true
    ports:
    - 7700:7700
    deploy:
      resources:
        limits:
          memory: 512m
