# docker-compose.yml
version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: zrp.rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:alpine
    container_name: zrp.redis
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
        - "6379:6379"

  api:
    image: leandrolasnor/ruby:zrp
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: zrp.api
    stdin_open: true
    tty: true
    command: sh
    environment:
      MEILISEARCH_ACCESS_KEY: key
      MEILISEARCH_URL: http://meilisearch:7700/
      AMQP_SERVER: amqp://rabbitmq:5672
      SOCKET_IO_SERVER: http://api
      SOCKET_IO_SERVER_PORT: 3003
      INSURGENCY_TIME: 30000
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3003:3003"
    depends_on:
      - redis
      - db

  db:
    image: bitnami/postgresql:latest
    container_name: zrp.postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: zrp
    ports:
      - "5432:5432"

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: zrp.meilisearch
    environment:
      MEILI_MASTER_KEY: key
      MEILI_NO_ANALYTICS: true
    ports:
      - "7700:7700"
