# docker-compose.yml
services:
  rabbitmq:
    image: rabbitmq:management
    # mem_limit: 128m
    container_name: zrp.rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
    - 15672:15672

  redis:
    image: redis:alpine
    # mem_limit: 28m
    container_name: zrp.redis
    environment:
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD}
    ports:
    - 6379

  api:
    image: devcontainer:ruby-3.4.2-slim
    # mem_limit: 6g
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      target: devcontainer
      args:
        RUBY_VERSION: ${RUBY_VERSION}
    container_name: zrp.api
    command: ["tail", "-f", "/dev/null"]
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_TEST: ${DB_TEST}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_URL: ${MEILI_URL}
      AMQP_SERVER: ${AMQP_SERVER}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_URL: redis://${REDIS_HOST}:${REDIS_PORT}/0
      RAILS_MAX_THREADS: ${RAILS_MAX_THREADS}
      GRUF_CONTROLLERS_PATH: ${GRUF_CONTROLLERS_PATH}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RESQUE_DEBUG: ${RESQUE_DEBUG}
    ports:
    - 3000:3000
    - 28080:28080
    - 5600:5600

  db:
    image: postgres:15.14-bookworm
    # mem_limit: 128m
    container_name: zrp.postgresql
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
    - 5432
    volumes:
    - ../db/initdb:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    # mem_limit: 512m
    container_name: zrp.pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_SETUP_MASTER_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
    ports:
      - 8080:80

  meilisearch:
    image: getmeili/meilisearch:latest
    # mem_limit: 1g
    container_name: zrp.meilisearch
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_NO_ANALYTICS: ${MEILI_NO_ANALYTICS}
    ports:
    - 7700:7700
