development:
  MEILISEARCH_ACCESS_KEY: "key"
  MEILISEARCH_URL: "http://meilisearch:7700"
  AMQP_SERVER: "amqp://rabbitmq"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_URL: "redis://redis:6379/0"
  RAILS_MAX_THREADS: "4"

test:
  MEILISEARCH_ACCESS_KEY: "key"
  MEILISEARCH_URL: "http://meilisearch:7700"
  AMQP_SERVER: "amqp://rabbitmq"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_URL: "redis://redis:6379/0"
  RAILS_MAX_THREADS: "4"
