# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: threats.proto for package ''

require 'grpc'
require 'threats_pb'

module Threats
  class Service
    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Threats'

    rpc :CreateThreat, ::Threat, ::Threat
  end

  Stub = Service.rpc_stub_class
end
