# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: threats.proto

require 'google/protobuf'

descriptor_data = "\n\rthreats.proto\"O\n\x06Threat\x12\x13\n\x0bmonsterName\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x61ngerLevel\x18\x02 \x01(\t\x12\x1b\n\x08location\x18\x03 \x01(\x0b\x32\t.Location\"$\n\x08Location\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lng\x18\x02 \x01(\x02\x32+\n\x07Threats\x12 \n\x0c\x43reateThreat\x12\x07.Threat\x1a\x07.Threatb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

Threat = Google::Protobuf::DescriptorPool.generated_pool.lookup("Threat").msgclass
Location = Google::Protobuf::DescriptorPool.generated_pool.lookup("Location").msgclass
